# Generated by Django 2.0.10 on 2020-11-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_type', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_in', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('expired', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
