# Generated by Django 2.0.10 on 2020-11-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
